# ----------------------------
# Runtime
# ----------------------------
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 8080
ENV ASPNETCORE_URLS=http://+:8080

# ----------------------------
# Build + Publish
# ----------------------------
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src

# Copy csproj first (bolji caching)
COPY ["Rentify.WebAPI/Rentify.WebAPI.csproj", "Rentify.WebAPI/"]
COPY ["Rentify.Services/Rentify.Services.csproj", "Rentify.Services/"]
COPY ["Rentify.Model/Rentify.Model.csproj", "Rentify.Model/"]
COPY ["Rentify.EmailConsumer/Rentify.EmailConsumer.csproj", "Rentify.EmailConsumer/"]
RUN dotnet restore "Rentify.WebAPI/Rentify.WebAPI.csproj"

# Copy everything else
COPY . .
WORKDIR "/src/Rentify.WebAPI"

RUN dotnet publish "Rentify.WebAPI.csproj" \
    -c $BUILD_CONFIGURATION \
    -o /app/publish \
    /p:UseAppHost=false

# ----------------------------
# Final image
# ----------------------------
FROM base AS final
WORKDIR /app
COPY --from=build /app/publish .

ENTRYPOINT ["dotnet", "Rentify.WebAPI.dll"]
